from pathlib import Path
slugs=['aracsi-szepitok-balatonfured','euphoria-beauty-med-balatonfured','pure-white-beauty-balatonfured','agi-kozmetika-balatonfured','minnie-fodraszat-balatonfured','balassa-szalon-siofok','fellai-barber-shop-siofok','loreal-professionnel-siofok','barbershop-by-balassa-siofok','edina-fodraszat-siofok','selfie-fodraszat-siofok','szalonskicc-fodraszat-siofok','sd-beauty-project-keszthely','qubee-barbershop-keszthely','dreamhair-keszthely','pure-studio-keszthely','szipi-barbershop-keszthely','gold-hajstudio-keszthely','borbely-cafe-keszthely','dorka-fodrasza-keszthely']
css='''/*worker2-visual-v3*/.g0 .grid{grid-template-columns:1.35fr .65fr}.g0 .card:first-child{grid-row:span 2;min-height:360px}.g0 .card:first-child h3{font-size:clamp(2.2rem,4vw,4rem)}.g1 .grid{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;padding-bottom:10px}.g1 .card{flex:0 0 min(72vw,390px);scroll-snap-align:start;min-height:260px}.g2 .grid{grid-template-columns:repeat(12,1fr)}.g2 .card{grid-column:span 6}.g2 .card:nth-child(3n){grid-column:span 12}.g3 .grid{grid-template-columns:repeat(2,1fr);transform:rotate(-1deg)}.g3 .card:nth-child(even){transform:translateY(26px) rotate(1deg)}.g3 .card:nth-child(odd){border-radius:4px}.g4 .grid{grid-template-columns:1fr}.g4 .card{display:grid;grid-template-columns:72px 1fr auto;align-items:center;gap:20px;min-height:110px;border-radius:0;border-width:1px 0 0}.g4 .card h3{margin-top:0}.g4 .card p{margin:0}.g4 .card small{font-size:1rem}.g4 .card:last-child{border-bottom:1px solid color-mix(in srgb,var(--i) 13%,transparent)}@media(max-width:820px){.g0 .grid,.g2 .grid,.g3 .grid{display:grid;grid-template-columns:1fr;transform:none}.g0 .card:first-child,.g2 .card,.g2 .card:nth-child(3n){grid-column:auto;grid-row:auto;min-height:auto}.g3 .card:nth-child(even){transform:none}.g1 .card{flex-basis:82vw}.g4 .card{grid-template-columns:48px 1fr}.g4 .card p{grid-column:2}}'''
for i,slug in enumerate(slugs):
 p=Path(slug)/'index.html';s=p.read_text(encoding='utf-8')
 if 'worker2-visual-v3' in s: continue
 s=s.replace('</style>',css+'</style>',1)
 s=s.replace('<body class="f%d">'%(i%5),'<body class="f%d g%d">'%(i%5,i%5),1)
 p.write_text(s,encoding='utf-8')
print('WORKER2_VISUAL_V3',len(slugs))
