const { chromium } = require('playwright');
const fs = require('fs');
const slug='outreach/LD-005-023-orsi-zombori-kozmetika';
const base=`http://127.0.0.1:8765/${slug}/`;
const report={lead_id:'LD-005-023',checks:[],errors:[],result:'FAIL'};
const add=(name,pass,detail='')=>report.checks.push({name,pass,detail});
(async()=>{const browser=await chromium.launch({headless:true});try{for(const vp of [{name:'desktop',width:1440,height:900},{name:'mobile',width:390,height:844}]){const context=await browser.newContext({viewport:{width:vp.width,height:vp.height}});const page=await context.newPage();const ce=[],pe=[],fr=[];page.on('console',m=>{if(m.type()==='error')ce.push(m.text())});page.on('pageerror',e=>pe.push(String(e)));page.on('requestfailed',r=>fr.push(`${r.url()} :: ${r.failure()?.errorText||'failed'}`));const res=await page.goto(base,{waitUntil:'networkidle'});add(`${vp.name}.http2xx`,!!res&&res.status()>=200&&res.status()<300,String(res?.status()));add(`${vp.name}.console_errors`,ce.length===0,ce.join(' | '));add(`${vp.name}.page_errors`,pe.length===0,pe.join(' | '));add(`${vp.name}.failed_requests`,fr.length===0,fr.join(' | '));add(`${vp.name}.viewport_meta`,await page.locator('meta[name="viewport"]').count()===1);add(`${vp.name}.no_horizontal_overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),await page.evaluate(()=>`${document.documentElement.scrollWidth}/${innerWidth}`));add(`${vp.name}.no_placeholders`,!(await page.evaluate(()=>/lorem ipsum|\bTODO\b|PLACEHOLDER/i.test(document.body.innerText))));add(`${vp.name}.main_sections_visible`,!(await page.evaluate(()=>[...document.querySelectorAll('main section')].some(s=>{const r=s.getBoundingClientRect();return r.width<2||r.height<2}))));if(vp.name==='mobile'){await page.locator('.menu').click();add('mobile.menu_opens',await page.locator('.navlinks').evaluate(el=>el.classList.contains('open')));await page.locator('.navlinks a[href="#szolgaltatasok"]').click();add('mobile.menu_closes_after_link',!(await page.locator('.navlinks').evaluate(el=>el.classList.contains('open'))));}
await page.locator('a[href="#foglalas"]').first().click();await page.locator('.step[data-step="1"] .next').click();add(`${vp.name}.booking_validation_service`,await page.locator('#serviceError').evaluate(el=>el.classList.contains('show')));await page.locator('.choice').first().click();await page.locator('.step[data-step="1"] .next').click();add(`${vp.name}.booking_step2`,await page.locator('.step[data-step="2"]').evaluate(el=>el.classList.contains('active')));await page.locator('.datebtn').first().click();await page.locator('.slot').first().click();await page.locator('.step[data-step="2"] .next').click();await page.fill('#name','Teszt Anna');await page.fill('#email','anna@example.com');await page.locator('.step[data-step="3"] .next').click();add(`${vp.name}.booking_step4`,await page.locator('.step[data-step="4"]').evaluate(el=>el.classList.contains('active')));await page.locator('#finish').click();add(`${vp.name}.booking_success`,await page.locator('.step[data-step="5"]').evaluate(el=>el.classList.contains('active')));
await page.goto(base,{waitUntil:'networkidle'});await page.screenshot({path:`${slug}/${vp.name}-full.png`,fullPage:true});await page.goto(base,{waitUntil:'networkidle'});await page.screenshot({path:`${slug}/preview-${vp.name}.png`,fullPage:false});await context.close();}
const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const page=await context.newPage();await page.goto(base,{waitUntil:'networkidle'});add('reduced_motion.content_visible',!(await page.evaluate(()=>[...document.querySelectorAll('[data-reveal]')].some(x=>getComputedStyle(x).opacity==='0')));await context.close();report.result=report.checks.every(x=>x.pass)?'PASS':'FAIL';}catch(e){report.errors.push(String(e));}finally{await browser.close();fs.writeFileSync('worker5-ld005023-qa-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.result!=='PASS')process.exit(1);}})();