from pathlib import Path
slugs=['aracsi-szepitok-balatonfured','euphoria-beauty-med-balatonfured','pure-white-beauty-balatonfured','agi-kozmetika-balatonfured','minnie-fodraszat-balatonfured','balassa-szalon-siofok','fellai-barber-shop-siofok','loreal-professionnel-siofok','barbershop-by-balassa-siofok','edina-fodraszat-siofok','selfie-fodraszat-siofok','szalonskicc-fodraszat-siofok','sd-beauty-project-keszthely','qubee-barbershop-keszthely','dreamhair-keszthely','pure-studio-keszthely','szipi-barbershop-keszthely','gold-hajstudio-keszthely','borbely-cafe-keszthely','dorka-fodrasza-keszthely']
initials=['AS','EB','PW','ÁK','MF','BS','FB','LP','BB','EF','SF','SS','SD','QB','DH','PS','SB','GH','BC','DF']
extra='''.art b{position:absolute;z-index:1;font-size:clamp(4rem,10vw,9rem);line-height:.75;letter-spacing:-.08em;right:8%;top:10%;color:rgba(255,255,255,.72);font-family:Arial Black,Arial,sans-serif}.art.v0{background:linear-gradient(145deg,var(--a),color-mix(in srgb,var(--i) 92%,black))}.art.v1{background:repeating-linear-gradient(115deg,var(--a) 0 12%,color-mix(in srgb,var(--b) 18%,var(--i)) 12% 25%)}.art.v1:before{border-radius:0;transform:rotate(18deg);width:85%;left:-35%;top:30%}.art.v1:after{display:none}.art.v2{background:conic-gradient(from 210deg at 70% 35%,var(--a),color-mix(in srgb,var(--i) 92%,black),var(--a))}.art.v2:before{width:48%;left:8%;top:42%;border-width:10px}.art.v2:after{width:30%;left:55%;top:10%;border-width:1px}.art.v3{background:linear-gradient(90deg,color-mix(in srgb,var(--i) 94%,black) 0 38%,var(--a) 38% 62%,color-mix(in srgb,var(--b) 60%,var(--i)) 62%)}.art.v3:before{border-radius:0;width:110%;height:2px;left:-5%;top:35%;transform:rotate(-13deg)}.art.v3:after{border-radius:0;width:110%;height:2px;left:-5%;top:62%;transform:rotate(9deg)}.art.v4{background:radial-gradient(circle at 25% 25%,var(--a) 0 9%,transparent 10%),radial-gradient(circle at 76% 67%,color-mix(in srgb,var(--a) 70%,white) 0 21%,transparent 22%),color-mix(in srgb,var(--i) 94%,black)}.art.v4:before{width:72%;left:13%;top:14%;border-style:dashed}.art.v4:after{width:42%;left:44%;top:48%}.f0 h1,.f0 h2,.f0 h3{font-family:Georgia,serif;font-weight:500}.f1 h1,.f1 h2,.f1 h3{font-family:Arial Black,Arial,sans-serif}.f2 h1,.f2 h2,.f2 h3{font-family:Trebuchet MS,Arial,sans-serif}.f3 h1,.f3 h2,.f3 h3{font-family:Times New Roman,Georgia,serif;font-weight:500}.f4 h1,.f4 h2,.f4 h3{font-family:Verdana,Arial,sans-serif;letter-spacing:-.06em}.hero.center .art.v1{max-width:780px;margin-inline:auto}.hero.asym .art.v2{transform:translateY(34px)}.hero.editorial .art.v3{border-radius:4px}.hero.full .art.v4{filter:saturate(.9)}@media(max-width:820px){.hero.asym .art.v2{transform:none}.art b{font-size:clamp(4rem,24vw,7rem)}}'''
for i,(slug,ini) in enumerate(zip(slugs,initials)):
 p=Path(slug)/'index.html'; s=p.read_text(encoding='utf-8')
 if '/*worker2-visual-v2*/' in s: continue
 s=s.replace('</style>','/*worker2-visual-v2*/'+extra+'</style>',1)
 s=s.replace('<body>','<body class="f%d">'%(i%5),1)
 s=s.replace('<div class="art"><span class="tag">',f'<div class="art v{i%5}"><b>{ini}</b><span class="tag">',1)
 p.write_text(s,encoding='utf-8')
print('WORKER2_VISUAL_PATCH',len(slugs))
